### ISSUE TITLE
Problem accessing /grid/register

### ISSUE THREAD

**Issue by AJCastello** [vitormattos/whatsapp-client#2]
HI, i've finished the whole installation and it was really smooth and clean. But i don't know what i'am doing wrong and i cant register the session and even try the example.php.

After 'all green' running on Docker, accessing the log file, this is the first exception:

> ...
> selenium-hub_1 | 02:56:29.065 INFO [Hub.start] - Selenium Grid hub is up and running
> selenium-hub_1 | 02:56:29.067 INFO [Hub.start] - Nodes should register to http://172.24.0.2:4444/grid/register/
> selenium-hub_1 | 02:56:29.067 INFO [Hub.start] - Clients should connect to http://172.24.0.2:4444/wd/hub
> selenium-hub_1 | 2020-07-19 02:56:31.038:WARN:osjs.HttpChannel:qtp811587677-10: /grid/register
> selenium-hub_1 | java.lang.NullPointerException
> selenium-hub_1 | at java.util.TreeMap.rotateLeft(TreeMap.java:2226)
> selenium-hub_1 | at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2291)
> selenium-hub_1 | at java.util.TreeMap.put(TreeMap.java:582)
> ...

**continue a long exceptions list, then this:**

> ...
> selenium-hub_1 | at java.lang.Thread.run(Thread.java:748)
> selenium-hub_1 | 02:56:31.070 INFO [DefaultGridRegistry.add] - Registered a node http://172.24.0.4:5555
> selenium-hub_1 | 02:56:36.211 INFO [DefaultGridRegistry.add] - Registered a node http://172.24.0.3:5555
> selenium-hub_1 | 2020-07-19 03:08:19.701:WARN:osjs.HttpChannel:qtp811587677-15: /grid/register/
> selenium-hub_1 | org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: |Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'|System info: host: '5ef6f0ed406a', ip: '172.24.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.76-linuxkit', java.version: '1.8.0_252'|Driver info: driver.version: unknown
> selenium-hub_1 | at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:290)
> selenium-hub_1 | at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:220)
> selenium-hub_1 | at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
> ...

and the list goes on.

**About the environment**
Trying to access by the IP given on the console(like:  http://172.24.0.2:4444/) doesn't load a page, gives ERR_CONNECTION_TIMED_OUT

So i try *localhost*
http://localhost:4444/grid/console - shows chrome and firefox webdrivers working fine

Accessing http://localhost:4444/grid/register, gives:

> HTTP ERROR 500
> Problem accessing /grid/register. Reason:
> 
>     Server Error
> Caused by:
> org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
> System info: host: '5ef6f0ed406a', ip: '172.24.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.76-linuxkit', java.version: '1.8.0_252'
> Driver info: driver.version: unknown
> 	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:290)
> .....

Accessing http://localhost:4444/wd/hub gives a json:

> {
>   "sessionId": null,
>   "status": 13,
>   "value": {
>     "class": "java.lang.NullPointerException",
>     "error": "unknown error",
>     "message": null,
>     "stackTrace": [
>       {
>         "className": "org.openqa.grid.internal.ExternalSessionKey",
>         "fileName": "ExternalSessionKey.java",
>         "lineNumber": 79,
>         "methodName": "fromWebDriverRequest"
>       },
> ...

Please, help me!

**OS**
Windows 10

**Docker version**
Desktop 2.3.0.3

**Comment by vitormattos** [comment]
Hi,

I just saw your issue today. I did several refactors on the project, can you test again?

**Comment by vitormattos** [comment]
marked as resolved.
